<?php

namespace Database\Seeders;

use App\Models\Career;
use Illuminate\Database\Seeder;

class CareerDefinitionsSeeder extends Seeder
{
    public function run(): void
    {
        Career::query()->where('is_active', true)->get()->each(function (Career $career): void {
            $current = mb_strtolower(($career->description ?? '').' '.($career->study_focus ?? ''));
            $generic = blank($career->description) || blank($career->study_focus)
                || str_contains($current, 'en términos generales')
                || str_contains($current, 'oferta académica reconocida')
                || str_contains($current, 'esta carrera prepara profesionales');

            if (!$generic) return;

            [$object, $contents] = $this->definition($career->slug);
            $career->update([
                'description' => "{$career->name} estudia {$object}. Su formación integra teoría, análisis y práctica para comprender los problemas propios de este campo, seleccionar métodos adecuados y desarrollar soluciones responsables en contextos reales. Según el nivel académico, prepara para ejecutar procedimientos técnicos, gestionar procesos o diseñar e investigar soluciones de mayor complejidad.",
                'study_focus' => "El plan de estudios suele incluir {$contents}. Las materias exactas cambian entre instituciones y niveles, pero estos contenidos constituyen el núcleo formativo de la carrera.",
            ]);
        });
    }

    private function definition(string $slug): array
    {
        return match (true) {
            str_contains($slug, 'acuicultura'), $slug === 'piscicultura' => ['la reproducción, crianza, alimentación, sanidad y manejo sostenible de peces y otros organismos acuáticos, además de la calidad del agua y los sistemas productivos', 'biología acuática, limnología, calidad y gestión del agua, nutrición, reproducción, sanidad, diseño de estanques, producción, procesamiento y comercialización'],
            str_contains($slug, 'agroecologia') => ['los sistemas agrícolas como ecosistemas, combinando producción de alimentos, conservación de suelos y agua, biodiversidad y conocimientos de las comunidades', 'ecología, suelos, cultivos, semillas, manejo de plagas, agroforestería, recursos hídricos, economía rural, investigación participativa y producción sostenible'],
            str_contains($slug, 'agroindustr'), str_contains($slug, 'transformacion-de-alimentos') => ['la transformación de materias primas agrícolas y pecuarias en alimentos y otros productos con valor agregado, inocuidad y calidad', 'química y microbiología de alimentos, operaciones de transformación, conservación, maquinaria, control de calidad, inocuidad, envases, costos y gestión de plantas'],
            str_contains($slug, 'agronom') => ['la producción vegetal y el manejo científico de cultivos, suelos, agua y sanidad agrícola para obtener alimentos de forma productiva y sostenible', 'botánica, fisiología vegetal, edafología, riego, fitotecnia, entomología, fitopatología, mejoramiento, maquinaria, economía y extensión rural'],
            str_contains($slug, 'agropecuaria') => ['la planificación y gestión conjunta de la producción agrícola y pecuaria, considerando productividad, sanidad, territorio y sostenibilidad', 'cultivos, suelos, riego, nutrición y reproducción animal, sanidad vegetal y animal, maquinaria, administración rural y comercialización'],
            str_contains($slug, 'forestal'), str_contains($slug, 'agroforest') => ['los bosques y sistemas que integran árboles, cultivos y producción animal, buscando conservarlos, restaurarlos y aprovecharlos de manera sostenible', 'botánica forestal, dendrología, silvicultura, inventarios, suelos, cuencas, biodiversidad, sistemas agroforestales, teledetección, legislación y manejo forestal'],
            str_contains($slug, 'ambiental') => ['la prevención, medición y solución de impactos ambientales ocasionados por actividades humanas y procesos productivos', 'ecología, química ambiental, hidrología, contaminación de agua, aire y suelo, residuos, evaluación de impacto, sistemas de gestión, legislación y tecnologías de tratamiento'],
            str_contains($slug, 'alimentos') => ['la composición, transformación, conservación e inocuidad de los alimentos y el diseño y control de sus procesos industriales', 'química, bioquímica y microbiología de alimentos, balances de materia y energía, operaciones unitarias, conservación, análisis, inocuidad, calidad, envases y diseño de plantas'],
            str_contains($slug, 'administracion-de-hoteleria') => ['la gestión de alojamientos, servicios turísticos y experiencias de hospitalidad, articulando atención al cliente, operaciones y administración', 'recepción y alojamiento, alimentos y bebidas, costos, marketing turístico, calidad, eventos, legislación, idiomas, patrimonio y planificación de destinos'],
            str_contains($slug, 'administracion-rural') => ['la organización económica y productiva de empresas, asociaciones y proyectos del ámbito rural', 'administración, contabilidad, economía agrícola, costos, comercialización, cadenas productivas, formulación de proyectos, desarrollo territorial y extensión rural'],
            str_contains($slug, 'administracion') => ['cómo se planifican, organizan, dirigen y controlan los recursos y procesos de una organización para alcanzar objetivos sostenibles', 'administración, contabilidad, economía, finanzas, marketing, talento humano, operaciones, estadística, derecho empresarial, estrategia, proyectos y emprendimiento'],
            str_contains($slug, 'comercio-internacional') => ['el intercambio de bienes y servicios entre países y la gestión comercial, logística, aduanera y financiera que permite realizarlo', 'economía internacional, comercio exterior, legislación aduanera, logística, transporte, negociación, mercados, costos, finanzas, integración económica e idiomas'],
            str_contains($slug, 'economia-comunitaria') => ['la organización de la producción, distribución y consumo desde formas comunitarias, asociativas y solidarias vinculadas al territorio', 'economía, gestión comunitaria, contabilidad, producción, cadenas de valor, proyectos, políticas públicas, desarrollo territorial, saberes locales y sostenibilidad'],
            str_contains($slug, 'economia') => ['cómo personas, empresas y gobiernos producen, distribuyen y utilizan recursos, y cómo sus decisiones influyen en el bienestar y el desarrollo', 'microeconomía, macroeconomía, matemáticas, estadística, econometría, economía pública, monetaria, internacional y del desarrollo, investigación y formulación de políticas'],
            str_contains($slug, 'financiera') => ['la valoración, administración y control de recursos financieros, inversiones y riesgos mediante herramientas económicas, matemáticas y estadísticas', 'matemática financiera, contabilidad, economía, estadística, mercados de capitales, inversiones, riesgos, banca, evaluación de proyectos y modelos financieros'],
            str_contains($slug, 'contaduria') => ['el registro, medición, control e interpretación de las operaciones económicas y patrimoniales de organizaciones', 'contabilidad financiera y de costos, auditoría, tributación, presupuestos, finanzas, sistemas contables, control interno, legislación y ética profesional'],
            str_contains($slug, 'marketing') => ['las necesidades y conductas de los consumidores y la creación de estrategias para desarrollar, comunicar y posicionar productos, servicios y marcas', 'investigación de mercados, comportamiento del consumidor, estrategia, marca, publicidad, comunicación digital, ventas, analítica, precios y planificación de campañas'],
            str_contains($slug, 'secretariado') => ['la gestión eficiente de documentos, comunicaciones, agendas y procesos de apoyo administrativo en una organización', 'redacción y archivo, ofimática, gestión documental, contabilidad básica, atención al cliente, protocolo, organización de eventos, idiomas y asistencia gerencial'],
            str_contains($slug, 'automatizacion') => ['el control automático de máquinas y procesos industriales mediante sensores, actuadores, controladores y sistemas de supervisión', 'electricidad, electrónica, instrumentación, neumática, hidráulica, PLC, control, redes industriales, robótica, programación, mantenimiento y seguridad'],
            str_contains($slug, 'electricidad'), str_contains($slug, 'electrotecnia') => ['la instalación, operación, protección y mantenimiento de sistemas eléctricos utilizados en viviendas, industria y servicios', 'circuitos, máquinas eléctricas, instalaciones, mediciones, potencia, control, protecciones, planos, normativa, eficiencia energética y seguridad'],
            str_contains($slug, 'electromecan') => ['la integración de sistemas mecánicos y eléctricos presentes en máquinas, equipos e instalaciones industriales', 'mecánica, electricidad, máquinas eléctricas, dibujo técnico, materiales, control, automatización, montaje, diagnóstico, mantenimiento y seguridad industrial'],
            $slug === 'electronica', str_contains($slug, 'ingenieria-electronica') => ['el diseño y aplicación de circuitos y dispositivos que procesan señales, controlan equipos y permiten automatizar y comunicar sistemas', 'circuitos, electrónica analógica y digital, microcontroladores, señales, instrumentación, control, comunicaciones, programación, potencia y diseño electrónico'],
            str_contains($slug, 'telecomunicaciones') => ['la transmisión de voz, datos, imagen y video mediante redes alámbricas, inalámbricas, ópticas y satelitales', 'señales y sistemas, electrónica, redes, radiofrecuencia, antenas, fibra óptica, comunicaciones digitales, telefonía, seguridad, planificación y normativa del espectro'],
            str_contains($slug, 'informatica-industrial') => ['la aplicación de computación, redes y control digital a la supervisión y automatización de procesos industriales', 'programación, bases de datos, redes industriales, sistemas operativos, sensores, PLC, control, interfaces, mantenimiento y ciberseguridad industrial'],
            str_contains($slug, 'software') => ['los principios y procesos para analizar, diseñar, construir, probar, desplegar y mantener software confiable', 'programación, algoritmos, estructuras de datos, requisitos, arquitectura, bases de datos, pruebas, calidad, seguridad, experiencia de usuario, DevOps y gestión de proyectos'],
            str_contains($slug, 'sistemas'), str_contains($slug, 'informatica') => ['el tratamiento automático de información y el diseño e integración de software, datos, infraestructura y procesos tecnológicos', 'programación, algoritmos, bases de datos, arquitectura de computadores, sistemas operativos, redes, seguridad, ingeniería de software, análisis de sistemas y gestión tecnológica'],
            str_contains($slug, 'mecatronica') => ['la creación de máquinas y sistemas inteligentes integrando mecánica, electrónica, control y programación', 'cálculo, física, diseño mecánico, electrónica, sensores, actuadores, control, microcontroladores, robótica, programación, manufactura y mantenimiento'],
            str_contains($slug, 'mecanica-automotriz') => ['el funcionamiento, diagnóstico, mantenimiento y reparación de vehículos y sus sistemas mecánicos, eléctricos y electrónicos', 'motores, transmisión, frenos, suspensión, dirección, electricidad automotriz, inyección electrónica, diagnóstico, mantenimiento, seguridad y gestión de taller'],
            str_contains($slug, 'mecanica') => ['el diseño, fabricación, funcionamiento y mantenimiento de máquinas y sistemas que transforman movimiento, fuerza y energía', 'cálculo, física, dibujo y diseño mecánico, materiales, estática, dinámica, termodinámica, fluidos, manufactura, mantenimiento y gestión de proyectos'],
            str_contains($slug, 'metalurgica') => ['la extracción, concentración, transformación y tratamiento de metales y minerales para obtener materiales con propiedades controladas', 'mineralogía, química, termodinámica, preparación de minerales, metalurgia extractiva, fundición, tratamientos, materiales, control de procesos, ambiente y seguridad'],
            str_contains($slug, 'geologica') => ['la estructura y evolución de la Tierra aplicadas a la exploración de recursos, obras civiles, agua y prevención de riesgos geológicos', 'mineralogía, petrología, estratigrafía, tectónica, geomorfología, geología de campo, geofísica, hidrogeología, geotecnia, cartografía y evaluación de yacimientos'],
            str_contains($slug, 'petrole'), str_contains($slug, 'petroquim') => ['la exploración, extracción, procesamiento y transporte de hidrocarburos y, en petroquímica, su transformación en combustibles y productos industriales', 'geología, química, termodinámica, fluidos, yacimientos, perforación, producción, refinación, procesos, transporte, seguridad, ambiente y evaluación económica'],
            str_contains($slug, 'quimica-industrial') => ['la aplicación de la química al control y operación de procesos de fabricación de sustancias y productos a escala industrial', 'química analítica, orgánica e inorgánica, fisicoquímica, análisis instrumental, operaciones de proceso, control de calidad, tratamiento de residuos y seguridad'],
            str_contains($slug, 'ingenieria-quimica') => ['el diseño y optimización de procesos que transforman materias primas mediante cambios físicos, químicos o biológicos a escala industrial', 'cálculo, química, termodinámica, fenómenos de transporte, balances, operaciones unitarias, reactores, control, simulación, diseño de plantas, seguridad y ambiente'],
            str_contains($slug, 'arquitectura') => ['el diseño de espacios habitables y la relación entre personas, edificios, ciudad, cultura, tecnología y ambiente', 'diseño arquitectónico, dibujo, representación digital, historia, teoría, estructuras, construcción, instalaciones, urbanismo, paisaje, patrimonio y sostenibilidad'],
            str_contains($slug, 'construccion-civil') => ['la ejecución, organización y control técnico de obras de edificación e infraestructura', 'dibujo y lectura de planos, topografía, materiales, estructuras básicas, instalaciones, cómputos, presupuestos, programación de obra, seguridad y control de calidad'],
            str_contains($slug, 'ingenieria-civil') => ['el análisis, diseño, construcción y mantenimiento de infraestructura segura para vivienda, transporte, agua y servicios', 'cálculo, física, topografía, materiales, estructuras, geotecnia, hidráulica, saneamiento, carreteras, construcción, costos, gestión y normativa'],
            str_contains($slug, 'topografia') => ['la medición y representación precisa del terreno y la determinación de posiciones sobre la Tierra para obras, catastro y ordenamiento territorial', 'matemática, geometría, levantamientos, geodesia, cartografía, sistemas de coordenadas, GNSS, fotogrametría, SIG, catastro, replanteo y procesamiento de datos'],
            str_contains($slug, 'actividad-fisica') => ['el movimiento humano, el ejercicio y sus efectos sobre la salud, el rendimiento y la calidad de vida', 'anatomía, fisiología del ejercicio, biomecánica, entrenamiento, evaluación física, psicología, nutrición, recreación, actividad adaptada, investigación y gestión deportiva'],
            str_contains($slug, 'educacion-parvularia'), $slug === 'parvularia' => ['el desarrollo y aprendizaje de niñas y niños en la primera infancia y las estrategias para acompañarlos de forma segura, inclusiva y lúdica', 'desarrollo infantil, psicología, didáctica, lenguaje, juego, expresión artística, psicomotricidad, nutrición, inclusión, planificación, evaluación y práctica educativa'],
            str_contains($slug, 'fonoaudiologia') => ['la comunicación humana y sus alteraciones en el habla, lenguaje, voz, audición y deglución a lo largo de la vida', 'anatomía y fisiología, lingüística, acústica, audiología, desarrollo del lenguaje, evaluación, intervención en habla, voz y deglución, neurología, investigación y práctica clínica'],
            str_contains($slug, 'fisioterapia') => ['el movimiento y la función corporal para prevenir, evaluar y tratar limitaciones causadas por lesiones, enfermedades o discapacidad', 'anatomía, fisiología, biomecánica, kinesiología, evaluación funcional, ejercicio terapéutico, agentes físicos, rehabilitación musculoesquelética, neurológica y cardiorrespiratoria'],
            str_contains($slug, 'laboratorio-clinico') => ['el análisis de muestras biológicas para apoyar la prevención, diagnóstico, seguimiento y control de enfermedades', 'anatomía, bioquímica, microbiología, hematología, inmunología, parasitología, toma y manejo de muestras, análisis instrumental, bioseguridad y control de calidad'],
            str_contains($slug, 'laboratorio-dental') => ['el diseño y fabricación técnica de prótesis, aparatos y restauraciones dentales prescritos por profesionales de odontología', 'anatomía dental, oclusión, materiales, encerado, prótesis fija y removible, ortodoncia, cerámica, procesos digitales, bioseguridad y gestión de laboratorio'],
            str_contains($slug, 'optometria') => ['la función visual y la detección y corrección de problemas refractivos y binoculares dentro de su ámbito profesional', 'anatomía y fisiología ocular, óptica, refracción, visión binocular, contactología, baja visión, instrumentación, salud ocular, atención primaria y práctica clínica'],
            str_contains($slug, 'veterinaria') => ['la salud, enfermedad, bienestar, reproducción y producción de animales, así como su relación con la salud pública y los alimentos de origen animal', 'anatomía y fisiología animal, microbiología, parasitología, patología, farmacología, clínica y cirugía, reproducción, nutrición, producción pecuaria, epidemiología e inocuidad'],
            str_contains($slug, 'musica') => ['la creación, interpretación y comprensión de la música mediante el dominio técnico de la voz o instrumentos y el análisis de sus lenguajes', 'teoría, solfeo, entrenamiento auditivo, armonía, historia, instrumento o canto, ensamble, composición, arreglos, pedagogía, tecnología musical y práctica escénica'],
            str_contains($slug, 'teatro') => ['la creación y representación escénica de acciones y relatos mediante actuación, cuerpo, voz, dirección y producción', 'actuación, expresión corporal y vocal, improvisación, dramaturgia, historia del teatro, dirección, puesta en escena, escenografía, iluminación, producción y pedagogía'],
            str_contains($slug, 'artes-plasticas') => ['la creación y análisis de imágenes y objetos artísticos mediante lenguajes visuales, materiales y procesos contemporáneos y tradicionales', 'dibujo, pintura, escultura, grabado, composición, color, historia y teoría del arte, fotografía, medios digitales, investigación, montaje y gestión cultural'],
            str_contains($slug, 'diseno-de-interiores') => ['la planificación de espacios interiores funcionales, seguros y expresivos de acuerdo con las necesidades de sus usuarios', 'dibujo, representación digital, ergonomía, materiales, iluminación, color, mobiliario, instalaciones, construcción, historia del diseño, presupuestos y gestión de proyectos'],
            str_contains($slug, 'belleza-integral') => ['el cuidado estético de la piel, cabello, manos y cuerpo mediante procedimientos cosméticos no médicos y atención profesional al cliente', 'anatomía y cosmetología básica, diagnóstico estético, higiene y bioseguridad, tratamientos faciales y corporales, peluquería, colorimetría, manicure, maquillaje, productos y gestión de servicios'],
            str_contains($slug, 'teologia') => ['las creencias, textos, tradiciones y prácticas religiosas, especialmente cristianas, mediante análisis histórico, filosófico y pastoral', 'estudios bíblicos, historia de las religiones y de la Iglesia, teología sistemática, ética, filosofía, hermenéutica, lenguas bíblicas, pastoral, investigación y diálogo intercultural'],
            default => ['el campo de conocimientos, técnicas y problemas que define esta profesión y su aplicación en organizaciones, comunidades o procesos productivos', 'fundamentos de la disciplina, métodos de análisis, herramientas técnicas, investigación, comunicación profesional, ética, gestión de proyectos y práctica aplicada'],
        };
    }
}
