<?php

namespace Database\Seeders;

use App\Models\LearningVideo;
use App\Models\Opportunity;
use Illuminate\Database\Seeder;

class OpportunitiesSeeder extends Seeder
{
    public function run(): void
    {
        $checked = now();
        $items = [
            ['course','belleza-integral-moderna-dallas','Belleza integral: peluquería, manicura y cosmetología','Centro de Capacitación Técnica Privado Moderna Dallas','Formación práctica en estilismo, cortes, colorimetría, maquillaje, manicura y belleza capilar y facial.','Presencial','paid',null,'Consultar según programa','Jóvenes y adultos; consultar edad mínima','Consultar documentos, materiales y requisitos del programa elegido.','Contactar a la sede de Quillacollo o Sacaba y confirmar grupo, horario, costo total y certificación.','Consultar mediante sus canales oficiales','Quillacollo y Sacaba, Cochabamba',null,null,'consult',null,'https://heylink.me/InstitutoModernaDallas/'],
            ['course','canto-virtual-gospel-music','Curso virtual de canto para principiantes','Gospel Music School','Técnica vocal inicial, respiración, uso de la voz, reconocimiento de registro y práctica con repertorio elegido por el estudiante.','Virtual','paid',20,'Acceso virtual; consultar vigencia','Personas sin conocimientos previos de canto','Conexión a internet y registro en la plataforma.','Registrarse en la página, seleccionar el curso y revisar las opciones de pago habilitadas.','63830956 / 72714800','Bolivia — en línea',null,null,'open',null,'https://gospelvirtual.com/?course=3&data-course='],
            ['course','formacion-musical-ars-tunari','Formación musical: canto e instrumentos','Ars Tunari — Centro de Capacitación Artística Musical','Cursos intensivos, talleres individuales y grupales de canto, guitarra, contrabajo, coro y otras áreas musicales.','Presencial','consult',null,'Según programa','Niñas, niños, jóvenes, adultos y adultos mayores','Los menores deben asistir al proceso de entrevista con sus padres o tutores.','Completar la preinscripción, realizar entrevista y evaluación de ubicación; luego confirmar pago y horario.','arstunari@gmail.com','Av. Linde N.º 40, Cochabamba',null,null,'open','Matrícula liberada durante la gestión 2026, según publicación institucional.','https://www.arstunari.art/'],
            ['course','talleres-danza-y-arte-apilla','Talleres de danza, dibujo y pintura','Centro Cultural de Arte Apilla','Talleres de danza folclórica, salón, internacional, zumba, danza moderna, dibujo y pintura.','Presencial','consult',null,'Consultar por disciplina','Niños, adolescentes, jóvenes y adultos','Consultar nivel, edad y materiales con el centro.','Comunicarse con el centro para conocer horarios, mensualidad y cupos del grupo elegido.','77949860','Calle Cleomendez Blanco, Colcapirhua',null,null,'consult',null,'https://apilla.com.bo/'],
            ['course','capacitacion-danza-ebid','Cursos cortos de capacitación en danza','Escuela Boliviana Intercultural de Danza — EBID','Cursos cortos que acercan a la comunidad a distintas disciplinas y expresiones de danza.','Presencial','consult',null,'2 meses en la oferta publicada','Niñas, niños, jóvenes y adultos','Varían según el curso y nivel anunciado.','Revisar la categoría de cursos de capacitación y consultar la siguiente fecha disponible.','2-816466 / 77786222','Bolivia',null,null,'consult',null,'https://ebid.edu.bo/index.php/cursos-de-capacitacion/'],
            ['course','cursos-tecnicos-infocal-2026','Cursos técnicos cortos 2026','Instituto Tecnológico INFOCAL Cochabamba','Capacitación práctica en informática, redes, soporte, electricidad, electrónica, gastronomía, mecánica, robótica y automatización.','Presencial','consult',null,'Curso corto; depende del módulo','Estudiantes, trabajadores, jóvenes profesionales y público general','Dependen del nivel y módulo seleccionado.','Consultar el calendario 2026, sede, fechas, costo y cupos antes de inscribirse.','4242660 / infocal@infocalcbba.edu.bo','Tupuraya y Arocagua, Cochabamba',null,null,'open',null,'https://www.infocalcbba.edu.bo/capacitacion-actualizazada/'],
            ['course','curso-ingles-esiex','Inglés básico, intermedio y avanzado','Escuela de Idiomas Extranjeros — Ministerio de Educación','Programa público de capacitación progresiva en idioma inglés mediante niveles básico, intermedio y avanzado.','Consultar convocatoria','consult',null,'Según nivel','Postulantes que cumplan la convocatoria vigente','Revisar edad, documentación, cupos y condiciones en la convocatoria del Ministerio de Educación.','Consultar la próxima convocatoria oficial y seguir su procedimiento de inscripción.','Ministerio de Educación','Bolivia',null,null,'consult',null,'https://www.minedu.gob.bo/index.php/index.php/pages/programa-100-becas.html'],
            ['training','capacitacion-externa-aduana','Capacitaciones externas en procedimientos aduaneros','Aduana Nacional de Bolivia','Plataforma oficial con cursos virtuales, presenciales y semipresenciales sobre operación y procedimientos aduaneros.','Virtual, presencial o semipresencial','consult',null,'Depende de la convocatoria','Operadores, estudiantes o grupos definidos en cada edición','Registro y perfil requerido según el curso disponible.','Ingresar al sistema oficial, revisar cursos habilitados y completar la inscripción solicitada.','800-10-5001 / capacitacionexterna@aduana.gob.bo','La Paz y modalidad virtual',null,null,'open',null,'https://moodle.aduana.gob.bo/capacitacion-externa/'],
            ['training','gestion-bioriesgo-inlasa','Gestión del biorriesgo','Instituto Nacional de Laboratorios de Salud — INLASA','Capacitación especializada para fortalecer prácticas de gestión y prevención de riesgos biológicos.','Consultar','consult',null,'24 horas','Personal o estudiantes vinculados con laboratorios y salud; confirmar convocatoria','Perfil y documentos definidos por INLASA.','Revisar la ficha vigente del curso y consultar disponibilidad, fechas y costo.','2-2226048 / 2-2225196','Miraflores, La Paz',null,null,'consult',null,'https://inlasa.gob.bo/cursos-de-capacitacion/'],
            ['training','prevencion-violencia-egpp','Prevención de la violencia — versión 23','Escuela de Gestión Pública Plurinacional — EGPP','Curso virtual orientado a comprender y prevenir distintas formas de violencia desde el servicio y la responsabilidad pública.','Virtual','consult',null,'2 semanas','Público definido en la ficha de inscripción','Registro en el sistema académico y cumplimiento de las actividades.','Consultar en la plataforma si aún existen cupos o esperar una nueva versión.','EGPP','En línea',new \DateTime('2026-09-07'),null,'open',null,'https://webdisk.cursos.egpp.gob.bo/sisacademico/oferta/web/prevencion-de-la-violencia-ver23'],
            ['scholarship','becas-google-career-launchpad-2026','Programa Nacional de 5.000 Becas Google','Ministerio de Educación, AGETIC y Google','Acceso gratuito a rutas internacionales de inteligencia artificial generativa, nube, ciberseguridad, analítica de datos e ingeniería de nube, con certificados e insignias digitales.','Virtual','free',0,'Según la ruta seleccionada','Jóvenes bolivianos desde los 18 años','Ser boliviano y cumplir las condiciones que publique la convocatoria y las instituciones participantes.','Revisar el anuncio y el formulario oficial que habiliten el Ministerio de Educación o AGETIC; no entregar dinero a intermediarios.','Ministerio de Educación / AGETIC','Todo Bolivia',null,null,'consult','5.000 becas para jóvenes y 100 becas para facilitadores digitales.','https://www.minedu.gob.bo/index.php?Itemid=854&catid=182%3Anoticias&id=8445%3Aalianza-gob-google-5000-becas-jovenes&option=com_content&view=article'],
            ['scholarship','programa-becas-jovenes-bolivia','Programa de Becas para Jóvenes','Ministerio de Educación de Bolivia','Programa estatal que reúne becas de formación profesional y tecnológica en áreas empresariales, sociales, salud, informática, diseño, gastronomía y otras.','Presencial o virtual','free',0,'Depende de cada beca','Jóvenes bolivianos; la edad y condición académica varían por convocatoria','Registro gratuito y evaluación o documentación según la convocatoria correspondiente.','La convocatoria 2026 publicada ya tuvo etapas con fechas específicas; consultar la próxima apertura únicamente en el portal oficial.','Ministerio de Educación','Todo Bolivia',null,null,'consult',null,'https://www.minedu.gob.bo/index.php?Itemid=854&catid=182&id=8250%3Aprograma-de-becas-para-jovenes-gestion-2026&option=com_content&view=article'],
            ['scholarship','oferta-becas-egpp','Convocatorias de becas internacionales canalizadas','Escuela de Gestión Pública Plurinacional — EGPP','Boletines oficiales que reúnen becas de posgrado y cursos cortos ofrecidos por organismos y gobiernos internacionales para postulantes de Bolivia.','Presencial o virtual','free',0,'Varía según el programa','Público general o profesionales, según cada convocatoria','Cada beca define grado académico, idioma, edad, experiencia y documentos propios.','Consultar el boletín más reciente, verificar el plazo y postular solamente mediante el enlace oficial señalado.','EGPP','Bolivia y exterior',null,null,'consult',null,'https://egpp.gob.bo/'],
        ];
        foreach ($items as $i) {
            [$type,$slug,$title,$provider,$description,$modality,$costType,$cost,$duration,$audience,$requirements,$process,$contact,$location,$start,$deadline,$status,$promo,$url] = $i;
            Opportunity::updateOrCreate(['slug'=>$slug], compact('type','title','provider','description','modality','duration','audience','requirements','contact','location') + [
                'cost_type'=>$costType,'cost_amount'=>$cost,'currency'=>$slug==='canto-virtual-gospel-music'?'USD':'BOB','application_process'=>$process,'start_date'=>$start,'deadline'=>$deadline,
                'availability_status'=>$status,'promotion_text'=>$promo,'official_url'=>$url,'verified_at'=>$checked,'is_verified'=>true,'is_active'=>true,
            ]);
        }
        foreach ([
            ['Conceptos básicos de electrónica para reparar celulares','8yOXb8-Pc3k','i2C Tech','Reparación de celulares','Introducción gratuita a fundamentos de electrónica aplicados a teléfonos.'],
            ['Ejercicio de técnica y recuperación vocal','BdKroh5GUJ0','Superior Singing Method','Canto profesional','Ejercicio breve para explorar el entrenamiento y cuidado de la voz.'],
            ['Conversación sobre formación profesional en danza','KFSfBIFyr-w','Mentalidades','Danza profesional','Experiencia y criterios sobre la formación y el trabajo profesional en danza.'],
        ] as [$title,$youtubeId,$channel,$area,$description]) {
            LearningVideo::updateOrCreate(['youtube_id'=>$youtubeId], ['title'=>$title,'channel'=>$channel,'career_area'=>$area,'description'=>$description,'is_active'=>true]);
        }

        $this->call(OpportunityEnhancementsSeeder::class);
    }
}
