<?php
namespace Database\Seeders;
use App\Models\{Career,Department,Institution};use Illuminate\Database\Seeder;
class OruroInstitutionsSeeder extends Seeder{
private const GUIDE='https://www.minedu.gob.bo/files/documentos-normativos/VESFP/2024/reglamentos/GUIA-INSTITUTOS-2024-OCTUBRE.pdf';
public function run():void{$d=Department::where('slug','oruro')->firstOrFail();$rows=[
['universidad-tecnica-de-oruro','Universidad Técnica de Oruro','UTO','Universidad','Pública','Gratuita','Oruro','Av. 6 de Octubre N.º 5715, entre Cochabamba y Ayacucho','https://www.uto.edu.bo/',['ingenieria-civil','ingenieria-minera','ingenieria-geologica','ingenieria-metalurgica','ingenieria-mecanica','ingenieria-electrica','ingenieria-electronica','ingenieria-de-sistemas','ingenieria-industrial','ingenieria-quimica','arquitectura','ingenieria-agronomica','medicina-veterinaria-y-zootecnia','medicina','enfermeria','odontologia','nutricion-y-dietetica','derecho','psicologia','trabajo-social','ciencia-politica-y-gestion-publica','economia','administracion-de-empresas','contaduria-publica','ingenieria-comercial']],
['universidad-privada-de-oruro','Universidad Privada de Oruro','UNIOR','Universidad','Privada','De pago','Oruro','Calle Potosí esquina Junín N.º 348','https://www.unior.edu.bo/',['administracion-de-empresas','contaduria-publica','ingenieria-de-sistemas','gastronomia','turismo','derecho','odontologia','medicina','enfermeria','protesis-dental'],'60431888'],
['universidad-privada-domingo-savio-oruro','Universidad Privada Domingo Savio - Oruro','UPDS','Universidad','Privada','De pago','Oruro','Calle Villazón, entre La Plata y Presidente Montes','https://www.upds.edu.bo/sede/oruro/',['ingenieria-de-sistemas','ingenieria-industrial','ingenieria-civil','arquitectura','administracion-de-empresas','contaduria-publica','ingenieria-comercial','derecho','psicologia','comunicacion-social']],
['instituto-tecnologico-iai-oruro','Instituto Tecnológico IAI','IAI','Instituto técnico/tecnológico','De convenio','Mixta','Oruro','Ciudad de Oruro',null,['automatizacion-industrial','mecanica-industrial','mecanica-automotriz','electronica']],
['instituto-superior-comercio-insco-esae-oruro','Instituto Superior de Comercio INSCO-ESAE','INSCO','Instituto técnico/tecnológico','Fiscal','Gratuita','Oruro','Zona Central, ciudad de Oruro',null,['contaduria-general','sistemas-informaticos','secretariado-ejecutivo','administracion-de-empresas']],
['instituto-tecnico-jesus-maria-i','Instituto Técnico Jesús María I','JM I','Instituto técnico/tecnológico','De convenio','Mixta','Oruro','Ciudad de Oruro',null,['sistemas-informaticos','secretariado-ejecutivo','telecomunicaciones']],
['instituto-tecnico-jesus-maria-ii','Instituto Técnico Jesús María II','JM II','Instituto técnico/tecnológico','De convenio','Mixta','Oruro','Ciudad de Oruro',null,['sistemas-informaticos','secretariado-ejecutivo','telecomunicaciones']],
['instituto-tecnico-superior-cieba','Instituto Técnico Superior CIEBA','CIEBA','Instituto técnico/tecnológico','Fiscal','Gratuita','Oruro','Ciudad de Oruro',null,['enfermeria']],
['instituto-tecnologico-superior-caracollo','Instituto Tecnológico Superior Caracollo','ITSCA','Instituto técnico/tecnológico','Fiscal','Gratuita','Caracollo','Plaza 25 de Julio, calles Bolívar y Oruro',null,['ingenieria-agropecuaria','construccion-civil','gastronomia']],
['instituto-tecnologico-agroindustrial-sajama','Instituto Tecnológico Agroindustrial Sajama','ITAS','Instituto técnico/tecnológico','Fiscal','Gratuita','Corque','Zona Central, municipio de Corque',null,['ingenieria-agropecuaria']],
['instituto-tecnologico-superior-santiago-huari','Instituto Tecnológico Superior Santiago de Huari','ITSH','Instituto técnico/tecnológico','Fiscal','Gratuita','Santiago de Huari','Zona Central, Santiago de Huari',null,['quimica-industrial','construccion-civil']],
['instituto-tecnologico-san-pedro-totora','Instituto Tecnológico Agroindustrial San Pedro de Totora','ITSPT','Instituto técnico/tecnológico','Fiscal','Gratuita','San Pedro de Totora','Zona Central, San Pedro de Totora',null,['mecanica-automotriz','industria-textil-y-confeccion','ingenieria-agropecuaria','veterinaria-y-zootecnia']],
['instituto-tecnologico-superior-saucari','Instituto Tecnológico Superior Saucari','ITSSA','Instituto técnico/tecnológico','Fiscal','Gratuita','Toledo','Zona Central, municipio de Toledo',null,['mecanica-automotriz','veterinaria-y-zootecnia']],
['instituto-tecnologico-superior-marka-qaqachaca','Instituto Tecnológico Superior Marka Qaqachaca','ITSMAQ','Instituto técnico/tecnológico','Fiscal','Gratuita','Challapata','Ciudad de Challapata','https://itsmaq-web.netlify.app/',['mecanica-automotriz']],
['instituto-tecnologico-superior-marka-aroma','Instituto Tecnológico Superior Marka Aroma','ITSMA','Instituto técnico/tecnológico','Fiscal','Gratuita','Salinas de Garci Mendoza','Zona Central, Salinas de Garci Mendoza',null,['mecanica-automotriz','electronica','industria-de-alimentos']],
['instituto-tecnologico-superior-huanuni','Instituto Tecnológico Superior Huanuni','ITS-HU','Instituto técnico/tecnológico','Fiscal','Gratuita','Huanuni','Ciudad de Huanuni',null,['gastronomia','quimica-industrial']],
['instituto-superior-musica-maria-luisa-luzio','Instituto Superior de Música María Luisa Luzio','ISML','Instituto artístico','Fiscal','Gratuita','Oruro','Ciudad de Oruro',null,['musica']],
['instituto-superior-bellas-artes-maria-delgadillo','Instituto Superior de Bellas Artes María Delgadillo','ISBA','Instituto artístico','Fiscal','Gratuita','Oruro','Ciudad de Oruro',null,['artes-plasticas-y-visuales']],
];foreach($rows as $r)$this->save($d->id,$r);}
private function save(int $did,array $r):void{[$slug,$name,$acr,$type,$own,$pay,$city,$address,$web,$slugs]=$r;$phone=$r[10]??null;$i=Institution::updateOrCreate(['slug'=>$slug],['department_id'=>$did,'name'=>$name,'acronym'=>$acr,'institution_type'=>$type,'ownership'=>$own,'payment_type'=>$pay,'description'=>($type==='Universidad'?'Universidad':'Institución de educación superior')." ubicada en {$city}, con oferta académica formal.",'cost_notes'=>$pay==='Gratuita'?'Confirmar matrícula, materiales y valores administrativos.':'Consultar aranceles con la institución.','schedule_notes'=>'Consultar horarios según carrera y gestión.','city'=>$city,'address'=>$address,'phone'=>$phone,'website'=>$web,'source_url'=>$web?:self::GUIDE,'is_verified'=>true,'verified_at'=>now(),'is_active'=>true]);foreach(Career::whereIn('slug',$slugs)->get() as $c)$i->careers()->syncWithoutDetaching([$c->id=>['degree_level'=>$type==='Universidad'?'Licenciatura':'Técnico Superior','modality'=>'Presencial','schedule'=>'Consultar con la institución','duration_text'=>$c->duration_text?:($type==='Universidad'?'Consultar plan de estudios':'3 años'),'labor_demand'=>'Variado','labor_demand_notes'=>null,'is_active'=>true]]);}}
