<?php
namespace Database\Seeders;
use App\Models\{Career,Department,Institution};use Illuminate\Database\Seeder;
class PotosiInstitutionsSeeder extends Seeder{
private const GUIDE='https://www.minedu.gob.bo/files/documentos-normativos/VESFP/2024/reglamentos/GUIA-INSTITUTOS-2024-OCTUBRE.pdf';
public function run():void{$d=Department::where('slug','potosi')->firstOrFail();$rows=[
['universidad-autonoma-tomas-frias','Universidad Autónoma Tomás Frías','UATF','Universidad','Pública','Gratuita','Potosí','Calle Serrudo s/n esquina avenida Cívica','https://www.uatf.edu.bo/',['medicina','enfermeria','ingenieria-civil','ingenieria-industrial','ingenieria-de-sistemas','ingenieria-electrica','ingenieria-mecanica','ingenieria-minera','ingenieria-geologica','ingenieria-agronomica','arquitectura','artes-plasticas-y-visuales','derecho','trabajo-social','economia','administracion-de-empresas','contaduria-publica']],
['universidad-nacional-siglo-xx','Universidad Nacional Siglo XX','UNSXX','Universidad','Pública','Gratuita','Llallagua','Zona Salvadora, ciudad de Llallagua','https://unsxx.bo/',['ingenieria-agronomica','topografia-y-geodesia','mecanica-automotriz','ingenieria-informatica','ingenieria-electromecanica','ingenieria-civil','bioquimica','quimica-farmaceutica','enfermeria','laboratorio-clinico','odontologia','medicina','fisioterapia-y-kinesiologia','comunicacion-social','ciencias-de-la-educacion','derecho','contaduria-publica']],
['universidad-privada-domingo-savio-potosi','Universidad Privada Domingo Savio - Potosí','UPDS','Universidad','Privada','De pago','Potosí','Av. Unión esquina Gareca','https://www.upds.edu.bo/sede/potosi/',['ingenieria-de-sistemas','ingenieria-industrial','ingenieria-civil','arquitectura','administracion-de-empresas','contaduria-publica','ingenieria-comercial','derecho','psicologia','comunicacion-social','fisioterapia-y-kinesiologia']],
['instituto-tecnologico-superior-potosi','Instituto Tecnológico Superior Potosí','ITSP','Instituto técnico/tecnológico','Fiscal','Gratuita','Potosí','Ciudad de Potosí, zona urbana',null,['ingenieria-agropecuaria','construccion-civil','electricidad-industrial','mecanica-industrial','sistemas-informaticos','industria-textil-y-confeccion']],
['instituto-tecnico-incos-potosi','Instituto Técnico INCOS Potosí','INCOS','Instituto técnico/tecnológico','Fiscal','Gratuita','Potosí','Ciudad de Potosí, zona Central',null,['contaduria-general','secretariado-ejecutivo','sistemas-informaticos','administracion-de-empresas']],
['instituto-tecnico-pio-xii-llallagua','Instituto Técnico Superior Pío XII','PIO XII','Instituto técnico/tecnológico','Fiscal','Gratuita','Llallagua','Zona Central, ciudad de Llallagua',null,['sistemas-informaticos','contaduria-general','secretariado-ejecutivo']],
['instituto-tecnologico-superior-charcas','Instituto Tecnológico Superior Charcas','ITSCH','Instituto técnico/tecnológico','Fiscal','Gratuita','San Pedro de Buena Vista','Zona Central, San Pedro de Buena Vista',null,['construccion-civil','mecanica-automotriz','industria-de-alimentos','gastronomia']],
['instituto-superior-comercio-daniel-campos','Instituto Técnico Superior Daniel Campos INSCO','INSCO','Instituto técnico/tecnológico','Fiscal','Gratuita','Uyuni','Zona Central, ciudad de Uyuni',null,['administracion-de-empresas','contaduria-general','secretariado-ejecutivo']],
['instituto-tecnologico-superior-uyuni','Instituto Tecnológico Superior Uyuni','ITSU','Instituto técnico/tecnológico','Fiscal','Gratuita','Uyuni','Ciudad de Uyuni, provincia Antonio Quijarro','https://www.tecnologicouyuni.org/',['mecanica-automotriz','electricidad-industrial','sistemas-informaticos','turismo','gastronomia']],
['instituto-tecnologico-zootecnia-tomave','Instituto Tecnológico de Zootecnia Tomave','ITZT','Instituto técnico/tecnológico','Fiscal','Gratuita','Tomave','Zona Central, municipio de Tomave',null,['veterinaria-y-zootecnia','ingenieria-agropecuaria']],
['instituto-tecnologico-superior-simon-bolivar-potosi','Instituto Tecnológico Superior Simón Bolívar','ITSB','Instituto técnico/tecnológico','Fiscal','Gratuita','Potosí','Ciudad de Potosí',null,['mecanica-automotriz','electricidad-industrial','electronica','sistemas-informaticos']],
['instituto-tecnologico-superior-nuevo-amanecer','Instituto Tecnológico Superior Nuevo Amanecer','ITSNA','Instituto técnico/tecnológico','Fiscal','Gratuita','Potosí','Comunidad San Andrés de Machaca, municipio de Potosí',null,['ingenieria-agropecuaria','veterinaria-y-zootecnia','industria-de-alimentos']],
['instituto-tecnico-centenario','Instituto Técnico Centenario','ITC','Instituto técnico/tecnológico','Fiscal','Gratuita','Potosí','Ciudad de Potosí',null,['contaduria-general','secretariado-ejecutivo','sistemas-informaticos']],
['instituto-tecnologico-tupiza','Instituto Tecnológico Superior Tupiza','ITST','Instituto técnico/tecnológico','Fiscal','Gratuita','Tupiza','Zona Central, ciudad de Tupiza',null,['mecanica-automotriz','sistemas-informaticos','turismo','gastronomia']],
['instituto-tecnico-corporativo-empresarial-cce-villazon','Instituto Técnico Corporativo Empresarial CCE','CCE','Instituto técnico/tecnológico','Privada','De pago','Villazón','Av. Antofagasta N.º 402 y calle Cochabamba, zona El Parque',null,['secretariado-ejecutivo','administracion-de-empresas','contaduria-general']],
];foreach($rows as $r)$this->save($d->id,$r);}
private function save(int $did,array $r):void{[$slug,$name,$acr,$type,$own,$pay,$city,$address,$web,$slugs]=$r;$i=Institution::updateOrCreate(['slug'=>$slug],['department_id'=>$did,'name'=>$name,'acronym'=>$acr,'institution_type'=>$type,'ownership'=>$own,'payment_type'=>$pay,'description'=>($type==='Universidad'?'Universidad':'Institución técnica superior')." ubicada en {$city}, con oferta académica formal.",'cost_notes'=>$pay==='Gratuita'?'Confirmar matrícula, materiales y valores administrativos.':'Consultar aranceles con la institución.','schedule_notes'=>'Consultar horarios según carrera y gestión.','city'=>$city,'address'=>$address,'website'=>$web,'source_url'=>$web?:self::GUIDE,'is_verified'=>true,'verified_at'=>now(),'is_active'=>true]);foreach(Career::whereIn('slug',$slugs)->get() as $c)$i->careers()->syncWithoutDetaching([$c->id=>['degree_level'=>$type==='Universidad'?'Licenciatura':'Técnico Superior','modality'=>'Presencial','schedule'=>'Consultar con la institución','duration_text'=>$c->duration_text?:($type==='Universidad'?'Consultar plan de estudios':'3 años'),'labor_demand'=>'Variado','labor_demand_notes'=>null,'is_active'=>true]]);}}
