<?php
namespace Database\Seeders;
use App\Models\{Career,Department,Institution};use Illuminate\Database\Seeder;
class TarijaInstitutionsSeeder extends Seeder{
private const GUIDE='https://www.minedu.gob.bo/files/documentos-normativos/VESFP/2024/reglamentos/GUIA-INSTITUTOS-2024-OCTUBRE.pdf';
public function run():void{$d=Department::where('slug','tarija')->firstOrFail();$rows=[
['universidad-autonoma-juan-misael-saracho','Universidad Autónoma Juan Misael Saracho','UAJMS','Universidad','Pública','Gratuita','Tarija','Av. Víctor Paz Estenssoro N.º 149','https://www.uajms.edu.bo/',['derecho','economia','contaduria-publica','administracion-de-empresas','ingenieria-agronomica','ingenieria-forestal','ingenieria-ambiental','ingenieria-civil','ingenieria-quimica','ingenieria-de-sistemas','ingenieria-petrolera','medicina','enfermeria','odontologia','bioquimica','arquitectura','psicologia','comunicacion-social','turismo','medicina-veterinaria-y-zootecnia']],
['universidad-catolica-boliviana-tarija','Universidad Católica Boliviana San Pablo - Sede Tarija','UCB','Universidad','Privada','De pago','Tarija','Calle Colón N.º 734, zona Central','https://tja.ucb.edu.bo/',['administracion-de-empresas','ingenieria-comercial','contaduria-publica','derecho','psicologia','ingenieria-de-sistemas','arquitectura']],
['universidad-privada-domingo-savio-tarija','Universidad Privada Domingo Savio - Tarija','UPDS','Universidad','Privada','De pago','Tarija','Av. Los Sauces esquina Fabián Ruiz','https://www.upds.edu.bo/sede/tarija/',['ingenieria-de-sistemas','ingenieria-industrial','ingenieria-civil','arquitectura','administracion-de-empresas','contaduria-publica','ingenieria-comercial','derecho','psicologia','comunicacion-social']],
['instituto-tecnologico-tarija','Instituto Tecnológico Tarija','ITT','Instituto técnico/tecnológico','Fiscal','Gratuita','Tarija','Zona Morros Blancos, ciudad de Tarija',null,['mecanica-automotriz','mecanica-industrial','electricidad-industrial','electronica','sistemas-informaticos']],
['instituto-comercial-superior-tarija-incos','Instituto Comercial Superior Tarija INCOS','INCOS','Instituto técnico/tecnológico','Fiscal','Gratuita','Tarija','Zona Central, ciudad de Tarija',null,['contaduria-general','secretariado-ejecutivo','sistemas-informaticos','administracion-de-empresas']],
['instituto-tecnologico-san-andres-tarija','Instituto Tecnológico Agropecuario San Andrés','ITSA','Instituto técnico/tecnológico','Fiscal','Gratuita','Tarija','Comunidad San Andrés, municipio de Tarija',null,['ingenieria-agropecuaria','veterinaria-y-zootecnia','industria-de-alimentos']],
['instituto-tecnologico-san-ignacio-loyola-tarija','Instituto Tecnológico San Ignacio de Loyola','ITSIL','Instituto técnico/tecnológico','De convenio','Mixta','Tarija','Ciudad de Tarija',null,['contaduria-general','sistemas-informaticos','secretariado-ejecutivo','gastronomia']],
['instituto-tecnologico-uriondo','Instituto Tecnológico Uriondo','ITU','Instituto técnico/tecnológico','Fiscal','Gratuita','Uriondo','Valle de la Concepción, municipio de Uriondo',null,['ingenieria-agropecuaria','industria-de-alimentos','turismo']],
['instituto-tecnologico-emborozu','Instituto Tecnológico Emborozú','ITE','Instituto técnico/tecnológico','Fiscal','Gratuita','Padcaya','Comunidad Emborozú, municipio de Padcaya',null,['ingenieria-agropecuaria','veterinaria-y-zootecnia','industria-de-alimentos']],
['instituto-tecnologico-bermejo','Instituto Tecnológico Bermejo','ITB','Instituto técnico/tecnológico','Fiscal','Gratuita','Bermejo','Ruta Nacional N.º 33, km 10, colonia José María Linares','https://www.itbermejo.org/',['mecanica-automotriz','industria-textil-y-confeccion','construccion-civil','mecanica-industrial','electromecanica-industrial'],'73450646'],
['instituto-tecnologico-yacuiba','Instituto Tecnológico Yacuiba','ITY','Instituto técnico/tecnológico','Fiscal','Gratuita','Yacuiba','Ciudad de Yacuiba, provincia Gran Chaco',null,['quimica-industrial','mecanica-automotriz','electricidad-industrial','sistemas-informaticos']],
['instituto-tecnologico-superior-villa-montes','Instituto Tecnológico Superior Villa Montes','ITSVM','Instituto técnico/tecnológico','Fiscal','Gratuita','Villa Montes','Barrio Bolívar, ciudad de Villa Montes',null,['industria-de-la-madera','mecanica-automotriz','electricidad-industrial','ingenieria-agropecuaria']],
['instituto-tecnologico-eustaquio-mendez','Instituto Tecnológico Eustaquio Méndez','ITEM','Instituto técnico/tecnológico','Fiscal','Gratuita','San Lorenzo','Municipio de San Lorenzo',null,['industria-de-alimentos','ingenieria-agropecuaria','turismo']],
['instituto-tecnologico-yunchara','Instituto Tecnológico Yunchará','ITYU','Instituto técnico/tecnológico','Fiscal','Gratuita','Yunchará','Zona Central, municipio de Yunchará',null,['construccion-civil','ingenieria-agropecuaria','turismo']],
['instituto-tecnologico-oconnor','Instituto Tecnológico O’Connor','ITO','Instituto técnico/tecnológico','Fiscal','Gratuita','Entre Ríos','Zona Central, municipio de Entre Ríos',null,['topografia-y-geodesia','ingenieria-ambiental','ingenieria-agropecuaria']],
['instituto-tecnologico-san-alberto','Instituto Tecnológico San Alberto','ITSA','Instituto técnico/tecnológico','Fiscal','Gratuita','Caraparí','Municipio de Caraparí, provincia Gran Chaco',null,['industria-de-alimentos','turismo','ingenieria-agropecuaria']],
['instituto-tecnologico-2-agosto-iscayachi','Instituto Tecnológico 2 de Agosto - Iscayachi','ITIA','Instituto técnico/tecnológico','Fiscal','Gratuita','Iscayachi','Localidad de Iscayachi, municipio de El Puente',null,['ingenieria-agropecuaria','veterinaria-y-zootecnia']],
];foreach($rows as $r)$this->save($d->id,$r);}
private function save(int $did,array $r):void{[$slug,$name,$acr,$type,$own,$pay,$city,$address,$web,$slugs]=$r;$phone=$r[10]??null;$i=Institution::updateOrCreate(['slug'=>$slug],['department_id'=>$did,'name'=>$name,'acronym'=>$acr,'institution_type'=>$type,'ownership'=>$own,'payment_type'=>$pay,'description'=>($type==='Universidad'?'Universidad':'Institución técnica superior')." ubicada en {$city}, con oferta académica formal.",'cost_notes'=>$pay==='Gratuita'?'Confirmar matrícula, materiales y valores administrativos.':'Consultar aranceles con la institución.','schedule_notes'=>'Consultar horarios según carrera y gestión.','city'=>$city,'address'=>$address,'phone'=>$phone,'website'=>$web,'source_url'=>$web?:self::GUIDE,'is_verified'=>true,'verified_at'=>now(),'is_active'=>true]);foreach(Career::whereIn('slug',$slugs)->get() as $c)$i->careers()->syncWithoutDetaching([$c->id=>['degree_level'=>$type==='Universidad'?'Licenciatura':'Técnico Superior','modality'=>'Presencial','schedule'=>'Consultar con la institución','duration_text'=>$c->duration_text?:($type==='Universidad'?'Consultar plan de estudios':'3 años'),'labor_demand'=>'Variado','labor_demand_notes'=>null,'is_active'=>true]]);}}
