@extends('admin.layout') @section('title',($item->exists?'Editar ':'Agregar ').$title) @section('heading',($item->exists?'Editar ':'Agregar ').Str::lower($title)) @section('content')
<form class="admin-form panel" method="POST" action="{{ $item->exists?route('admin.content.update',[$resource,$item->id]):route('admin.content.store',$resource) }}">@csrf @if($item->exists)@method('PUT')@endif @if($errors->any())<div class="form-alert">Revisa los campos marcados.<ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($resource==='institutions')
<label>Nombre<input name="name" value="{{ old('name',$item->name) }}" required></label><label>Departamento<select name="department_id" required>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id',$item->department_id)==$department->id)>{{ $department->name }}</option>@endforeach</select></label><label>Sigla<input name="acronym" value="{{ old('acronym',$item->acronym) }}"></label><label>Tipo de institución<input name="institution_type" value="{{ old('institution_type',$item->institution_type) }}" required></label><label>Gestión<input name="ownership" value="{{ old('ownership',$item->ownership) }}"></label><label>Costo<input name="payment_type" value="{{ old('payment_type',$item->payment_type) }}"></label><label>Ciudad<input name="city" value="{{ old('city',$item->city) }}" required></label><label>Dirección<input name="address" value="{{ old('address',$item->address) }}" required></label><label>Teléfono<input name="phone" value="{{ old('phone',$item->phone) }}"></label><label>Correo<input type="email" name="email" value="{{ old('email',$item->email) }}"></label><label class="wide">Sitio web<input type="url" name="website" value="{{ old('website',$item->website) }}"></label><label class="wide">Descripción<textarea name="description">{{ old('description',$item->description) }}</textarea></label>
@elseif($resource==='careers')
<label>Nombre<input name="name" value="{{ old('name',$item->name) }}" required></label><label>Área académica<select name="academic_area_id"><option value="">Sin área</option>@foreach($areas as $area)<option value="{{ $area->id }}" @selected(old('academic_area_id',$item->academic_area_id)==$area->id)>{{ $area->name }}</option>@endforeach</select></label><label>Nivel o título<input name="degree_level" value="{{ old('degree_level',$item->degree_level) }}" required></label><label>Duración<input name="duration_text" value="{{ old('duration_text',$item->duration_text) }}"></label><label class="wide">Resumen<textarea name="summary" required>{{ old('summary',$item->summary) }}</textarea></label><label class="wide">Descripción<textarea name="description">{{ old('description',$item->description) }}</textarea></label><label class="wide">Campo profesional<textarea name="professional_field">{{ old('professional_field',$item->professional_field) }}</textarea></label><label class="check"><input type="checkbox" name="is_traditional" value="1" @checked(old('is_traditional',$item->is_traditional??true))> Carrera tradicional</label>
@else
<label>Título<input name="title" value="{{ old('title',$item->title) }}" required></label><label>Institución responsable<input name="provider" value="{{ old('provider',$item->provider) }}" required></label><label>Tipo<select name="type"><option value="course" @selected(old('type',$item->type)==='course')>Curso</option><option value="training" @selected(old('type',$item->type)==='training')>Capacitación</option><option value="scholarship" @selected(old('type',$item->type)==='scholarship')>Beca</option></select></label><label>Estado<select name="availability_status"><option value="open">Disponible</option><option value="consult">Consultar</option><option value="closed">Finalizada</option></select></label><label>Modalidad<input name="modality" value="{{ old('modality',$item->modality) }}"></label><label>Costo<select name="cost_type"><option value="free">Gratuita</option><option value="paid">De pago</option><option value="consult">Consultar</option></select></label><label>Duración<input name="duration" value="{{ old('duration',$item->duration) }}"></label><label>Dirigido a<input name="audience" value="{{ old('audience',$item->audience) }}"></label><label class="wide">Fuente oficial<input type="url" name="official_url" value="{{ old('official_url',$item->official_url) }}" required></label><label class="wide">Descripción<textarea name="description" required>{{ old('description',$item->description) }}</textarea></label><label class="wide">Requisitos<textarea name="requirements">{{ old('requirements',$item->requirements) }}</textarea></label>
@endif
<input type="hidden" name="slug" value="{{ old('slug',$item->slug) }}"><label class="check"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$item->is_active??true))> Registro activo</label><div class="form-actions"><a href="{{ route('admin.content.index',$resource) }}">Cancelar</a><button class="admin-button">Guardar cambios</button></div></form>
@endsection
