<?php

return [
    'version' => '1.2',
    'questions' => [
        ['type' => 'R', 'text' => '¿Te gusta aprender haciendo, usar herramientas o descubrir cómo funciona un objeto antes que limitarte a leer instrucciones?', 'keywords' => ['mecán', 'automotr', 'electromec', 'mantenimiento']],
        ['type' => 'I', 'text' => 'Cuando surge un problema complejo, ¿disfrutas reunir información, comparar explicaciones y buscar la causa antes de decidir?', 'keywords' => ['medicina', 'salud', 'enfermer', 'odont', 'bioquím', 'farmac', 'fisioter']],
        ['type' => 'A', 'text' => '¿Te gustaría transformar ideas en imágenes, videos, fotografías, diseños o contenido digital?', 'keywords' => ['diseño', 'audiovisual', 'comunicación', 'fotograf', 'contenido', 'modelaje']],
        ['type' => 'S', 'text' => '¿Disfrutarías enseñar una materia y acompañar el aprendizaje de niños, jóvenes o adultos?', 'keywords' => ['educación', 'maestro', 'pedagog', 'idioma', 'lingüíst']],
        ['type' => 'E', 'text' => '¿Te gustaría crear un negocio, organizar un equipo y convertir una idea en un proyecto rentable?', 'keywords' => ['administración', 'marketing', 'comercial', 'emprend', 'negocio']],
        ['type' => 'C', 'text' => '¿Te sentirías cómodo registrando ingresos, revisando cuentas y preparando información financiera?', 'keywords' => ['contadur', 'finanzas', 'auditor', 'economía', 'tribut']],
        ['type' => 'R', 'text' => '¿Te atraería construir, medir terrenos o supervisar que una obra se ejecute correctamente?', 'keywords' => ['construcción', 'civil', 'topograf', 'arquitect', 'territorio']],
        ['type' => 'I', 'text' => '¿Disfrutarías programar una aplicación, proteger datos o resolver problemas de computación?', 'keywords' => ['sistemas', 'informática', 'software', 'comput', 'redes', 'ciberseg']],
        ['type' => 'A', 'text' => '¿Te gustaría crear música, escribir historias, actuar, bailar o producir una presentación artística?', 'keywords' => ['música', 'escrit', 'literat', 'teatro', 'baile', 'sonido', 'compositor']],
        ['type' => 'S', 'text' => '¿Sueles escuchar con atención, comprender lo que otra persona necesita y acompañarla para encontrar una solución?', 'keywords' => ['psicolog', 'trabajo social', 'orientación', 'terapia']],
        ['type' => 'E', 'text' => '¿Te sientes cómodo defendiendo una idea, convenciendo a otras personas y tomando decisiones en grupo?', 'keywords' => ['derecho', 'juríd', 'política', 'relaciones internacionales']],
        ['type' => 'C', 'text' => '¿Disfrutas ordenar información, seguir pasos claros y verificar que ningún detalle importante quede pendiente?', 'keywords' => ['secretariado', 'administración', 'archivo', 'gestión pública']],
        ['type' => 'R', 'text' => '¿Te gustaría cultivar, cuidar animales o aplicar técnicas para mejorar la producción del campo?', 'keywords' => ['agronom', 'agropec', 'veterinar', 'forestal', 'ambiental']],
        ['type' => 'I', 'text' => '¿Te interesaría trabajar en un laboratorio, realizar experimentos y explicar fenómenos naturales?', 'keywords' => ['biolog', 'química', 'física', 'laboratorio', 'biotecn', 'geolog']],
        ['type' => 'A', 'text' => '¿Disfrutas probar combinaciones nuevas y cuidar la presentación final de aquello que creas?', 'keywords' => ['gastronom', 'cocina', 'reposter', 'alimentos', 'hoteler']],
        ['type' => 'S', 'text' => '¿Te gustaría proteger a la comunidad, actuar con disciplina y responder ante situaciones de riesgo?', 'keywords' => ['polic', 'militar', 'seguridad', 'emergencia']],
        ['type' => 'E', 'text' => '¿Te interesaría promocionar productos, negociar con clientes y analizar oportunidades de mercado?', 'keywords' => ['marketing', 'ventas', 'comercio', 'publicidad', 'mercado']],
        ['type' => 'C', 'text' => '¿Te gustaría planificar rutas, inventarios y movimientos de productos con precisión?', 'keywords' => ['logística', 'aduana', 'comercio', 'transporte', 'industrial']],
        ['type' => 'R', 'text' => '¿Preferirías una actividad que te mantenga en movimiento o al aire libre durante buena parte del día?', 'keywords' => ['deport', 'fútbol', 'entrenamiento', 'actividad física']],
        ['type' => 'I', 'text' => '¿Te interesa comprender por qué funciona un sistema, probar posibles mejoras y comprobar los resultados?', 'keywords' => ['eléctr', 'electrón', 'automat', 'telecom', 'mecatrón']],
        ['type' => 'A', 'text' => '¿Te interesaría crear estilos de cabello, maquillaje, uñas o cuidado estético según cada cliente?', 'keywords' => ['estilismo', 'belleza', 'cosmet', 'peluquer', 'estética']],
        ['type' => 'S', 'text' => '¿Disfrutarías atender pacientes, personas mayores o familias que necesitan cuidado y orientación?', 'keywords' => ['enfermer', 'salud', 'geront', 'nutric', 'trabajo social']],
        ['type' => 'E', 'text' => '¿Te entusiasma presentar propuestas, asumir el liderazgo y movilizar a un grupo hacia una meta?', 'keywords' => ['comunicación', 'política', 'relaciones públicas', 'marketing', 'locución']],
        ['type' => 'C', 'text' => '¿Te sientes cómodo comparando datos, detectando diferencias y elaborando conclusiones detalladas?', 'keywords' => ['estadística', 'datos', 'informática', 'economía', 'actuarial']],
        ['type' => 'R', 'text' => '¿Te interesaría instalar redes, circuitos, equipos o sistemas que deben funcionar con seguridad?', 'keywords' => ['redes', 'electric', 'electrón', 'telecom', 'instalación']],
        ['type' => 'I', 'text' => '¿Disfrutarías investigar delitos, examinar evidencias o comprender el comportamiento humano?', 'keywords' => ['criminal', 'forense', 'derecho', 'psicolog', 'polic']],
        ['type' => 'A', 'text' => '¿Es importante para ti expresar tus ideas con una voz o estilo propio, aunque no exista una única forma correcta?', 'keywords' => ['contenido', 'comunicación', 'publicidad', 'audiovisual', 'influencer']],
        ['type' => 'S', 'text' => '¿Te motiva que tu trabajo contribuya de forma directa al bienestar o desarrollo de otras personas?', 'keywords' => ['nutric', 'fisioter', 'salud', 'terapia', 'medicina']],
        ['type' => 'E', 'text' => '¿Disfrutas coordinar personas y recursos para convertir una idea en una experiencia o proyecto concreto?', 'keywords' => ['turismo', 'hoteler', 'eventos', 'gastronom', 'servicios']],
        ['type' => 'C', 'text' => '¿Te agrada revisar tiempos, recursos y resultados para que un proceso se mantenga ordenado y cumpla lo planificado?', 'keywords' => ['industrial', 'producción', 'calidad', 'logística', 'alimentos']],
    ],
    'profiles' => [
        'R' => ['name' => 'Realista', 'phrase' => 'Acción, técnica y resultados concretos', 'strengths' => ['Practicidad', 'Constancia', 'Coordinación técnica'], 'description' => 'Tiendes a aprender haciendo y a desenvolverte bien en actividades prácticas, técnicas, físicas o vinculadas con entornos reales.'],
        'I' => ['name' => 'Investigador', 'phrase' => 'Análisis, curiosidad y descubrimiento', 'strengths' => ['Análisis', 'Curiosidad', 'Pensamiento lógico'], 'description' => 'Te motiva comprender cómo funcionan las cosas, estudiar evidencias y resolver problemas que requieren razonamiento.'],
        'A' => ['name' => 'Artístico', 'phrase' => 'Creatividad, expresión e innovación', 'strengths' => ['Creatividad', 'Comunicación', 'Originalidad'], 'description' => 'Valoras la libertad para crear, expresar ideas y desarrollar propuestas con una identidad propia.'],
        'S' => ['name' => 'Social', 'phrase' => 'Servicio, enseñanza y bienestar', 'strengths' => ['Empatía', 'Comunicación', 'Cooperación'], 'description' => 'Encuentras sentido en comprender, orientar, enseñar o contribuir al bienestar y desarrollo de otras personas.'],
        'E' => ['name' => 'Emprendedor', 'phrase' => 'Liderazgo, iniciativa y oportunidades', 'strengths' => ['Liderazgo', 'Persuasión', 'Iniciativa'], 'description' => 'Te atrae movilizar personas, asumir decisiones y convertir ideas en proyectos con impacto.'],
        'C' => ['name' => 'Convencional', 'phrase' => 'Organización, precisión y estabilidad', 'strengths' => ['Organización', 'Precisión', 'Responsabilidad'], 'description' => 'Te desempeñas bien con información detallada, procesos claros y responsabilidades que requieren orden y seguimiento.'],
    ],
];
