<!DOCTYPE html>
<html lang="es"><head><meta charset="utf-8"><title>Informe vocacional</title><style>
@page{margin:32px}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#17332b;font-size:10px;margin:0}.cover{background:#092e26;color:#fff;padding:30px;border-radius:8px}.brand{font-size:15px;font-weight:bold;color:#54d2aa}.cover h1{font-size:25px;line-height:1.25;margin:25px 0 10px}.cover p{color:#c4d5cf}.code{margin-top:22px;border-top:1px solid #41655a;padding-top:15px}.code strong{font-size:32px;color:#54d2aa;margin-right:12px}.label{color:#15956e;font-size:8px;font-weight:bold;letter-spacing:1px}.section{margin-top:20px;padding:18px;border:1px solid #dce5e1;border-radius:6px}.section h2{font-size:17px;margin:7px 0 10px;color:#092e26}.muted{color:#64716d;line-height:1.6}.strength{display:inline-block;background:#e4f6ef;color:#0f7659;padding:6px 8px;margin:4px;border-radius:4px}.bars{margin-top:12px}.bar-row{margin:8px 0}.bar-row b{display:inline-block;width:95px}.track{display:inline-block;width:300px;height:7px;background:#e5ece9}.fill{height:7px;background:#20b486}.career{border-bottom:1px solid #dce5e1;padding:12px 0;page-break-inside:avoid}.career h3{font-size:14px;margin:3px 0}.career p{margin:4px 0;color:#64716d}.match{color:#0f7659;font-weight:bold}.steps{background:#e4f6ef;padding:16px;margin-top:18px}.steps td{width:33%;vertical-align:top;padding:7px}.note{font-size:8px;color:#64716d;margin-top:18px;border-top:1px solid #dce5e1;padding-top:10px}.footer{text-align:center;font-size:8px;color:#81908b;margin-top:20px}
</style></head>
@php($letters = str_split($result->profile_code))
<body><div class="cover"><div class="brand">OrientaBo</div><h1>{{ $result->user->name }}, este es tu informe de orientación vocacional.</h1><p>Una lectura de tus intereses y cinco caminos académicos o profesionales para comenzar a explorar.</p><div class="code"><span class="label">CÓDIGO VOCACIONAL</span><br><strong>{{ $result->profile_code }}</strong> {{ collect($letters)->map(fn($letter) => $profiles[$letter]['name'])->join(' · ') }}</div></div>
<div class="section"><span class="label">INTERPRETACIÓN PERSONAL</span><h2>{{ $profiles[$letters[0]]['phrase'] }}</h2><p class="muted">{{ $result->interpretation }}</p>@foreach(collect($letters)->flatMap(fn($letter) => $profiles[$letter]['strengths'])->unique()->take(6) as $strength)<span class="strength">{{ $strength }}</span>@endforeach</div>
<div class="section"><span class="label">MAPA DE INTERESES</span><div class="bars">@foreach(collect($result->scores)->sortDesc() as $letter => $score)<div class="bar-row"><b>{{ $profiles[$letter]['name'] }}</b><span class="track"><span class="fill" style="display:block;width:{{ round(($score/15)*100) }}%"></span></span> {{ $score }}/15</div>@endforeach</div></div>
<div class="section"><span class="label">CINCO CAMINOS PARA EXPLORAR</span><h2>Carreras relacionadas con tu perfil</h2>@foreach($careers as $index => $career)<div class="career"><span class="label">OPCIÓN {{ $index + 1 }}</span><h3>{{ $career->name }}</h3><p>{{ Str::limit($career->summary, 230) }}</p><span class="match">Afinidad con {{ $profiles[$career->riasec_primary]['name'] ?? 'tu perfil' }}{{ $career->riasec_secondary ? ' y '.($profiles[$career->riasec_secondary]['name'] ?? '') : '' }}</span></div>@endforeach</div>
<div class="steps"><span class="label">PLAN DE ACCIÓN</span><table><tr><td><b>1. Explora</b><br>Investiga las opciones que despierten tu curiosidad.</td><td><b>2. Compara</b><br>Revisa contenidos, duración e instituciones.</td><td><b>3. Contrasta</b><br>Conversa con estudiantes o profesionales.</td></tr></table></div>
<p class="note"><b>Importante:</b> este instrumento identifica intereses declarados. No mide inteligencia, aptitudes clínicas ni determina una única profesión. Considera también tus habilidades, valores, situación personal y experiencias.</p><div class="footer">Informe N.º {{ $result->id }} · {{ $result->created_at->format('d/m/Y') }} · Test versión {{ $result->test_version }}</div></body></html>
